### ISSUE TITLE
claimChildren problems on opening sheetmetal saved file

### ISSUE THREAD

**Issue by kkoksvik** [shaise/FreeCAD_SheetMetal#1]
OS: "Arch Linux"
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.5465 (Git)
Build type: Unknown
Branch: makepkg
Hash: 347fe6217111569866fd83a4796d3d65e4e75dfe
Python version: 2.7.10
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 6.9.0

### When opening a file made with SheetMetal i get the following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
<type 'exceptions.ValueError'>: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
<type 'exceptions.ValueError'>: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/kjetil/.FreeCAD/Mod/SheetMetal/SheetMetalCmd.py", line 190, in claimChildren
    objs.append(self.Object.Proxy.baseObject)
<type 'exceptions.AttributeError'>: SMBendWall instance has no attribute 'baseObject'
Traceback (most recent call last):
  File "/home/kjetil/.FreeCAD/Mod/SheetMetal/SheetMetalCmd.py", line 190, in claimChildren
    objs.append(self.Object.Proxy.baseObject)
<type 'exceptions.AttributeError'>: SMBendWall instance has no attribute 'baseObject'
Traceback (most recent call last):
  File "/home/kjetil/.FreeCAD/Mod/SheetMetal/SheetMetalCmd.py", line 190, in claimChildren
    objs.append(self.Object.Proxy.baseObject)
<type 'exceptions.AttributeError'>: SMBendWall instance has no attribute 'baseObject'
Traceback (most recent call last):
  File "/home/kjetil/.FreeCAD/Mod/SheetMetal/SheetMetalCmd.py", line 190, in claimChildren
    objs.append(self.Object.Proxy.baseObject)
<type 'exceptions.AttributeError'>: SMBendWall instance has no attribute 'baseObject'
```

**Comment by shaise** [comment]
You are right. Taking a look now.

**Comment by shaise** [comment]
Hi Kkoksvik,

Thanks for sending this. Bug was fixed. Please try the updated version.

shai
