### ISSUE TITLE
Make Fold Wall command insensitive to selection order

### ISSUE THREAD

**Issue by jayennis22** [shaise/FreeCAD_SheetMetal#174]
The Fold Wall command requires that you select a face and an edge.  Order of selection is important.  If you select the edge then the face, you will get an error as follows:

```
19:37:13  Traceback (most recent call last):
  File "/Users/xxxx/Library/Preferences/FreeCAD/Mod/sheetmetal/SheetMetalFoldCmd.py", line 249, in execute
    s = smFold(bendR = fp.radius.Value, bendA = fp.angle.Value, flipped = fp.invert, unfold = fp.unfold, kfactor = fp.kfactor, bendlinesketch = fp.BendLine,
  File "/Users/xxxx/Library/Preferences/FreeCAD/Mod/sheetmetal/SheetMetalFoldCmd.py", line 98, in smFold
    normal = foldface.normalAt(0,0)
<class 'TypeError'>: function takes exactly 1 argument (2 given)
```

You must select the face first, then the edge.

**Comment by jaisekjames** [comment]
added here

https://github.com/shaise/FreeCAD_SheetMetal/pull/177

**Comment by luzpaz** [comment]
@jayennis22 care to test and confirm?  
@shaise can we close this?

**Comment by luzpaz** [comment]
> @jayennis22 care to test and confirm?
> @shaise can we close this?

ping

**Comment by shaise** [comment]
waiting for @jayennis22

**Comment by jayennis22** [comment]
The error condition as documented is fixed.  If you select the edge first and then the face, the Fold Wall icon is not enabled.  When you execute "Gui.runCommand('SMFoldWall',0)" in the Python console it fails silently.

I don't know what the design goals are for usability.  Perhaps this solution is considered sufficient.  However, I think it would be much more usable if SMFoldWall would instead accept an edge and a face in either order.  Failing that, SMFoldWall should at least provide a useful error message when the inputs are provided in the wrong order.

Leaving open for further review.  Thanks very much!

**Comment by luzpaz** [comment]
Shall we close and open a new ticket or rename this one ?

**Comment by shaise** [comment]
I think this can stay open, with added enhancement label

**Comment by luzpaz** [comment]
@shaise perhaps renaming ticket for clarity ?
