### ISSUE TITLE
Fold a Wall operator fails with "list index out of range"

### ISSUE THREAD

**Issue by johschmitz** [shaise/FreeCAD_SheetMetal#262]
I am running FreeCAD v0.20.2 with SheetMetal Workbench v0.2.60.
When I try to use the Fold a Wall operator it fails with the following error message:

```
21:32:41  1.0
21:32:41  Traceback (most recent call last):
  File "/home/schmitz/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalFoldCmd.py", line 260, in execute
    s = smFold(bendR = fp.radius.Value, bendA = fp.angle.Value, flipped = fp.invert, unfold = fp.unfold, kfactor = fp.kfactor, bendlinesketch = fp.BendLine,
  File "/home/schmitz/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalFoldCmd.py", line 155, in smFold
    solid0 = solid1list[0]
<class 'IndexError'>: list index out of range
21:32:41  Recompute failed! Please check report view.
```

Here a screenshots to show what I did just before clicking the button:
![Screenshot from 2023-01-23 21-32-36](https://user-images.githubusercontent.com/771979/214144811-34653877-cbac-4cfa-a02c-6946da2b0903.png)

**Comment by jaisekjames** [comment]
folding line should on selected face. It look like folding line on opposite face.

**Comment by johschmitz** [comment]
Can it not fold in both directions depending on which side the line is located?
