### ISSUE TITLE
why unfold  failed

### ISSUE THREAD

**Issue by arthur9188** [shaise/FreeCAD_SheetMetal#279]
Engineering mode is not enabled.
16:55:41  Manual K-factor is being used: 0.40 (ansi)
16:55:41  exception at line 3367('Removing splitter failed',)
16:55:41  ('Removing splitter failed',)
16:55:41  Traceback (most recent call last):
16:55:41    File "C:\Users\Administrator\AppData\Roaming\FreeCAD\Mod\sheetmetal\.\SheetMetalUnfolder.py", line 3367, in accept
    s, foldComp, norm, thename, err_cd, fSel, obN  = getUnfold(k_factor_lookup)
16:55:41    File "C:\Users\Administrator\AppData\Roaming\FreeCAD\Mod\sheetmetal\.\SheetMetalUnfolder.py", line 2645, in getUnfold
    TheTree = SheetTree(o.Object.Shape, f_number, k_factor_lookup) # initializes the tree-structure
16:55:41    File "C:\Users\Administrator\AppData\Roaming\FreeCAD\Mod\sheetmetal\.\SheetMetalUnfolder.py", line 452, in __init__
    withoutSplitter = self.__Shape.removeSplitter()
16:55:41  Part.OCCError: Removing splitter failed
16:55:41

**Comment by luzpaz** [comment]
* Missing [About](https://wiki.freecad.org/About) info
* Missing example file (zip and uploaded to github)
* Missing step-by-step instructions on how to recreate the issue

**Comment by arthur9188** [comment]
https://github.com/arthur9188/freecad-danguidiao

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[code]
OS: Windows 10 build 17763
Word size of FreeCAD: 64-bit
Version: 0.21.0.33345 (Git)
Build type: Release
Branch: master
Hash: a3c4f4bb01f5201daf666852444a8f9c5adbda8d
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Chinese/China (zh_CN)
Installed mods: 
  * A2plus 0.4.60n
  * Assembly4 0.50.2
  * sheetmetal 0.2.63
[/code]
